export const REGISTER_CONSULTATION = "app/RegisterConsultation/REGISTER_CONSULTATION";
export const REGISTER_CONSULTATION_SUCCESS = "app/RegisterConsultation/REGISTER_CONSULTATION_SUCCESS";
export const REGISTER_CONSULTATION_FAILURE = "app/RegisterConsultation/REGISTER_CONSULTATION_FAILURE";

export const GET_PATIENT_DETAILS_FOR_CONSULTATION = "app/ConsultationManagent/GET_PATIENT_DETAILS_FOR_CONSULTATION";
export const GET_PATIENT_DETAILS_FOR_CONSULTATION_SUCCESS = "app/ConsultationManagent/GET_PATIENT_DETAILS_FOR_CONSULTATION_SUCCESS";
export const GET_PATIENT_DETAILS_FOR_CONSULTATION_FAILURE = "app/ConsultationManagent/GET_PATIENT_DETAILS_FOR_CONSULTATION_FAILURE";

export const GET_ALL_COMMON_DATA = "app/ConsultationManagent/GET_ALL_COMMON_DATA";
export const GET_ALL_COMMON_DATA_SUCCESS = "app/ConsultationManagent/GET_ALL_COMMON_DATA_SUCCESS";
export const GET_ALL_COMMON_DATA_FAILURE = "app/ConsultationManagent/GET_ALL_COMMON_DATA_FAILURE";

export const GET_DISEASE_SPECIFIC_ALL_DATA = "app/ConsultationManagent/GET_DISEASE_SPECIFIC_ALL_DATA";
export const GET_DISEASE_SPECIFIC_ALL_DATA_SUCCESS = "app/ConsultationManagent/GET_DISEASE_SPECIFIC_ALL_DATA_SUCCESS";
export const GET_DISEASE_SPECIFIC_ALL_DATA_FAILURE = "app/ConsultationManagent/GET_DISEASE_SPECIFIC_ALL_DATA_FAILURE";

export const RESET_TO_INITIAL_STATE = "app/RegisterConsultation/RESET_TO_INITIAL_STATE" 