export const CREATE_DISEASES_AND_MEDICINE_MAPING = "app/DiseaseAndMedicineMappingManagement/CreateDiseasesAndMedicineMaping/CREATE_DISEASES_AND_MEDICINE_MAPING";
export const CREATE_DISEASES_AND_MEDICINE_MAPING_SUCCESS = "app/DiseaseAndMedicineMappingManagement/CreateDiseasesAndMedicineMaping/CREATE_DISEASES_AND_MEDICINE_MAPING_SUCCESS";
export const CREATE_DISEASES_AND_MEDICINE_MAPING_FAILURE = "app/DiseaseAndMedicineMappingManagement/CreateDiseasesAndMedicineMaping/CREATE_DISEASES_AND_MEDICINE_MAPING_FAILURE";

export const UPDATE_DISEASES_AND_MEDICINE_MAPING = "app/DiseaseAndMedicineMappingManagement/UpdateDiseasesAndMedicineMaping/UPDATE_DISEASES_AND_MEDICINE_MAPING";
export const UPDATE_DISEASES_AND_MEDICINE_MAPING_SUCCESS = "app/DiseaseAndMedicineMappingManagement/UpdateDiseasesAndMedicineMaping/UPDATE_DISEASES_AND_MEDICINE_MAPING_SUCCESS";
export const UPDATE_DISEASES_AND_MEDICINE_MAPING_FAILURE = "app/DiseaseAndMedicineMappingManagement/UpdateDiseasesAndMedicineMaping/UPDATE_DISEASES_AND_MEDICINE_MAPING_FAILURE";

export const GET_ALL_MAPPED_DISEASESANDMEDICINE = "app/DiseaseAndMedicineMappingManagement/getAllMappedDiseasesAndMedicine/GET_ALL_MAPPED_DISEASESANDMEDICINE";
export const GET_ALL_MAPPED_DISEASESANDMEDICINE_SUCCESS = "app/DiseaseAndMedicineMappingManagement/getAllMappedDiseasesAndMedicineSuccess/GET_ALL_MAPPED_DISEASESANDMEDICINE_SUCCESS";
export const GET_ALL_MAPPED_DISEASESANDMEDICINE_FAILURE = "app/DiseaseAndMedicineMappingManagement/getAllMappedDiseasesAndMedicineFailure/GET_ALL_MEDICINE_FAILURE";



export const RESET_TO_INITIAL_STATE = "app/DiseaseAndMedicineMappingManagement/RESET_TO_INITIAL_STATE" 