export const States = [ 
    {en:"Andhra Pradesh",hi:"आन्ध्र प्रदेश"},
    {en:"Arunachal Pradesh",hi:"अरुणाचल प्रदेश"},
    {en:"Assam",hi:"असम "},
    {en:"Bihar",hi:"बिहार"},
    {en:"Chhattisgarh",hi:"छत्तीसगढ़ "},
    {en:"Goa",hi:"गोवा"},
    {en:"Gujarat",hi:"गुजरात"},
    {en:"Haryana",hi:"हरयाणा"},
    {en:"Himachal Pradesh",hi:"हिमाचल प्रदेश"},
    {en:"Jammu and Kashmir",hi:"जम्मू और कश्मीर"},
    {en:"Jharkhand",hi:"झारखंड"},
    {en:"Karnataka",hi:"कर्नाटक"},
    {en:"Kerala",hi:"केरल"},
    {en:"Madhya Pradesh",hi:"मध्य प्रदेश"},
    {en:"Maharashtra",hi:"महाराष्ट्र"},
    {en:"Manipur",hi:"मणिपुर"},
    {en:"Meghalaya",hi:"मेघालय"},
    {en:"Mizoram",hi:"मिजोरम"},
    {en:"Nagaland",hi:"नगालैंड"},
    {en:"Odisha",hi:"ओडिशा"},
    {en:"Punjab",hi:"पंजाब"},
    {en:"Rajasthan",hi:"राजस्थान"},
    {en:"Sikkim",hi:"सिक्किम"},
    {en:"Tamil Nadu",hi:"तमिलनाडु"},
    {en:"Telangana",hi:"तेलंगाना"},
    {en:"Tripura",hi:"त्रिपुरा"},
    {en:"Uttarakhand",hi:"उत्तराखंड"},
    {en:"Uttar Pradesh",hi:"उत्तर प्रदेश"},
    {en:"West Bengal",hi:"पश्चिम बंगाल"},
    {en:"Andaman and Nicobar Islands",hi:"अंडमान व नोकोबार द्वीप समूह"},
    {en:"Chandigarh",hi:"चंडीगढ़"},
    {en:"Dadra and Nagar Haveli",hi:"दादरा एंड नगर हवेली"},
    {en:"Daman and Diu",hi:"दमन और दीव"},
    {en:"Delhi",hi:"दिल्ली"},
    {en:"Lakshadweep",hi:"लक्षद्वीप"},
    {en:"Puducherry",hi:"पुदुचेरी"}
    ]