export const REGISTER_PRE_CONSULTAION = "app/registerPreConsultation/REGISTER_PRE_CONSULTAION";
export const REGISTER_PRE_CONSULTAION_SUCCESS = "app/registerPreConsultation/REGISTER_PRE_CONSULTAION_SUCCESS";
export const REGISTER_PRE_CONSULTAION_FAILURE = "app/registerPreConsultation/REGISTER_PRE_CONSULTAION_FAILURE";

export const RESET_TO_INITIAL_STATE = "app/preConsultaion/RESET_TO_INITIAL_STATE"