export const CREATE_DISEASE_WITH_TIME_TABLE = "app/Diseases Map Time Table/CreateTimeTable/CREATE_DISEASE_WITH_TIME_TABLE";
export const CREATE_DISEASE_WITH_TIME_TABLE_SUCCESS = "app/Diseases Map Time Table/CreateTimeTable/CREATE_DISEASE_WITH_TIME_TABLE_SUCCESS";
export const CREATE_DISEASE_WITH_TIME_TABLE_FAILURE = "app/Diseases Map Time Table/CreateTimeTable/CREATE_DISEASE_WITH_TIME_TABLE_FAILURE";

export const UPDATE_DISEASE_WITH_TIME_TABLE  = "app/Diseases Map Time Table/UpdateTimeTable/UPDATE_DISEASE_WITH_TIME_TABLE";
export const UPDATE_DISEASE_WITH_TIME_TABLE_SUCCESS = "app/Diseases Map Time Table/UpdateTimeTable/UPDATE_DISEASE_WITH_TIME_TABLE_SUCCESS";
export const UPDATE_DISEASE_WITH_TIME_TABLE_FAILURE = "app/Diseases Map Time Table/UpdateTimeTable/UPDATE_DISEASE_WITH_TIME_TABLE_FAILURE";


export const GET_DISEASE_MAPPED_TIME_TABLE = "app/Diseases Map Time Table/GetTimeTables/GET_DISEASE_MAPPED_TIME_TABLE";
export const GET_DISEASE_MAPPED_TIME_TABLE_SUCCESS = "app/Diseases Map Time Table/GetTimeTables/GET_DISEASE_MAPPED_TIME_TABLE_SUCCESS";
export const GET_DISEASE_MAPPED_TIME_TABLE_FAILURE = "app/Diseases Map Time Table/GetTimeTables/GET_DISEASE_MAPPED_TIME_TABLE_FAILURE";


export const GET_DISEASE_MAPPED_MEDICINE = "app/Diseases Map Time Table/GetTimeTables/GET_DISEASE_MAPPED_MEDICINE";
export const GET_DISEASE_MAPPED_MEDICINE_SUCCESS = "app/Diseases Map Time Table/GetTimeTables/GET_DISEASE_MAPPED_MEDICINE_SUCCESS";
export const GET_DISEASE_MAPPED_MEDICINE_FAILURE = "app/Diseases Map Time Table/GetTimeTables/GET_DISEASE_MAPPED_MEDICINE_FAILURE";


export const RESET_TO_INITIAL_STATE = "app/Diseases Map Time Table/RESET_TO_INITIAL_STATE" 