export const GET_DISPENSARY_DATE_WISE_DATA = "app/ReportsManagement/GET_DISPENSARY_DATE_WISE_DATA";
export const GET_DISPENSARY_DATE_WISE_DATA_SUCCESS = "app/ReportsManagement/GET_DISPENSARY_DATE_WISE_DATA_SUCCESS";
export const GET_DISPENSARY_DATE_WISE_DATA_FAILURE = "app/ReportsManagement/GET_DISPENSARY_DATE_WISE_DATA_FAILURE";

export const RESET_TO_INITIAL_STATE = "app/ReportsManagement/RESET_TO_INITIAL_STATE"