export const DASHBOARD_ACCESS = "app/DashboardPage/DASHBOARD_ACCESS";
export const DASHBOARD_ACCESS_SUCCESS = "app/DashboardPage/DASHBOARD_ACCESS_SUCCESS";
export const DASHBOARD_ACCESS_FAILURE = "app/DashboardPage/DASHBOARD_ACCESS_FAILURE";

export const DASHBOARD_COUNTER_LIST = "app/DashboardPage/DASHBOARD_LIST";
export const DASHBOARD_COUNTER_SUCCESS = "app/DashboardPage/DASHBOARD_COUNTER_SUCCESS";
export const DASHBOARD_COUNTER_FAILURE = "app/DashboardPage/DASHBOARD_COUNTER_FAILURE";


export const DASHBOARD_RECENT_PATIENT_LIST = "app/DashboardPage/DASHBOARD_RECENT_PATIENT_LIST";
export const DASHBOARD_RECENT_PATIENT_SUCCESS = "app/DashboardPage/DASHBOARD_RECENT_PATIENT_SUCCESS";
export const DASHBOARD_RECENT_PATIENT_FAILURE = "app/DashboardPage/DASHBOARD_RECENT_PATIENT_FAILURE";


export const RESET_TO_INITIAL_STATE = "app/DashboardPage/RESET_TO_INITIAL_STATE"